#!/bin/bash

set -eux;

apk add --no-cache libuv; \

pre-built \
    --composer "2.8.1" \
    --node "22.2.0" \
    --php "8.2" \
    --php-extensions "dev,pear,phar,doc,apache2,bcmath,bz2,calendar,cgi,common,ctype,curl,dba,dbg,dom,embed,enchant,exif,ffi,fileinfo,fpm,ftp,gd,gettext,gmp,iconv,imap,intl,ldap,litespeed,mbstring,mysqli,mysqlnd,odbc,opcache,openssl,pcntl,pdo,pdo_dblib,pdo_mysql,pdo_odbc,pdo_pgsql,pdo_sqlite,pgsql,phpdbg,posix,pspell,session,shmop,simplexml,snmp,soap,sockets,sodium,sqlite3,sysvmsg,sysvsem,sysvshm,tidy,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,pecl-swoole,pecl-redis" \
    --build-pkg "build-base" \
    --build-pkg "libuv-dev" \
    --pecl-extension "uv=0.3.0" \
;