#!/bin/bash

set -eux;

apk add --no-cache \
    libuv \
;
builder \
    --nproc $(nproc) \
    --add-pkg "coreutils" \
    --add-pkg "gmp-dev" \
    --add-pkg "gcc" \
    --composer "2.7.9" \
    --nginx "1.27.1" \
    --pcre2 "10.43" \
    --zlib "1.3.1" \
    --libgd "2.3.3" \
    --openssl "3.3.0" \
    --nginx-with "openssl=/tmp/openssl" \
    --nginx-with "pcre=/tmp/pcre2" \
    --nginx-with "zlib=/tmp/zlib" \
    --nginx-with "pcre-jit" \
    --nginx-with "stream" \
    --nginx-with "threads" \
    --nginx-with "poll_module" \
    --nginx-with "select_module" \
    --nginx-with "http_ssl_module" \
    --nginx-with "stream_ssl_module" \
    --nginx-with "http_slice_module" \
    --nginx-with "http_gunzip_module" \
    --nginx-with "http_image_filter_module" \
    --nginx-without "http_grpc_module" \
    --node "22.2.0" \
    --php "8.3.12" \
    --php-with "mhash" \
    --php-with "pear" \
    --php-with "pic" \
    --php-with "sodium=shared" \
    --php-with "password-argon2" \
    --php-with "pdo-mysql=mysqlnd" \
    --php-with "pdo-sqlite=/usr" \
    --php-with "pdo-pgsql" \
    --php-with "sqlite3=/usr" \
    --php-with "iconv=/usr" \
    --php-with "readline" \
    --php-with "openssl" \
    --php-with "curl" \
    --php-with "zlib" \
    --php-with "bz2=/usr" \
    --php-with "zip" \
    --php-with "avif" \
    --php-with "webp" \
    --php-with "jpeg" \
    --php-enable "mbstring" \
    --php-enable "mysqlnd" \
    --php-enable "session" \
    --php-enable "phpdbg" \
    --php-enable "ctype" \
    --php-enable "phar" \
    --php-enable "pdo" \
    --php-enable "gd" \
    --php-enable "fpm" \
    --php-enable "ftp" \
    --php-enable "exif" \
    --php-enable "intl" \
    --php-enable "pcntl" \
    --php-enable "shmop" \
    --php-enable "bcmath" \
    --php-enable "opcache" \
    --php-enable "sockets" \
    --php-enable "fileinfo" \
    --php-enable "tokenizer" \
    --php-enable "short-tags" \
    --php-enable "opcache-jit" \
    --php-enable "phpdbg-readline" \
    --php-enable "option-checking=fatal" \
    --php-extension "swoole=5.1.1" \
    --php-extension "redis=6.0.2" \
    --php-extension "uv=0.3.0" \
;