#!/bin/bash

cd /var/www/

LANG=en_GB
TEXT_GIT_PULL='"git pull"'
PID=$(cat /var/run/supervisord.pid)

while true; do
    MESSAGE=$(git remote update && git status -uno | grep -o "$TEXT_GIT_PULL")
    if [ "$MESSAGE" == "$TEXT_GIT_PULL" ]; then
        git pull
        kill -9 $PID
        break;
    fi
    sleep 5
done