version: "3.1"
services:
    mariadb:
        restart: always
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${DB_DATABASE:-doravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-doravel}
            MYSQL_USER: ${DB_USERNAME:-doravel}
            MYSQL_TCP_PORT: ${DB_PORT:-3307}
        expose:
            - 3307
        volumes:
            - data-database:/var/lib/mysql
        networks:
            - default
networks:
    default:
        driver: bridge
volumes:
    data-database: