#!/bin/bash

rm -f data/php/composer;

while true; do
    echo " - downloading PHP Composer";

    curl -o data/php/composer https://getcomposer.org/composer-stable.phar;

    if [ ! -f data/php/composer ]; then
        echo "Failed to download PHP Composer"
        sleep 7
    else
        chmod +x data/php/composer;
        echo "Downloaded success PHP Composer"
        break
    fi
done