#!/bin/bash

sudo dnf -y install dnf-plugins-core git
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf -y install docker-ce docker-ce-cli containerd.io
sudo systemctl start docker
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

while true; do
    echo "Email de tu usuario GitHub: "
    read EMAIL
    
    if [[ $EMAIL =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$ ]]; then
        if [ ! -d $HOME/.ssh ]; then
            mkdir $HOME/.ssh
        fi
        if [ -f $HOME/.ssh/id_rsa.pub ]; then
            rm $HOME/.ssh/id_rsa.pub
        fi
        if [ -f $HOME/.ssh/id_rsa ]; then
            rm $HOME/.ssh/id_rsa
        fi
        
        echo "Nombre de tu usuario GitHub: "
        read NAME
        
        git config --global user.name "$NAME"
        git config --global user.email "$EMAIL"
        ssh-keygen -t rsa -b 4096 -C "$EMAIL" -f $HOME/.ssh/id_rsa -q -N ""
        
        echo ""
        echo "### SSH key generated ###"
        echo ""
        cat $HOME/.ssh/id_rsa.pub
        echo ""
        echo ""
        echo "⚠️⚠️ IMPORTANTE ⚠️⚠️"
        echo "No olvide agregar la clave pública a su repositorio de GitHub!"
        echo ""
        echo "👇️ ¿ eres dueño del proyecto ? 👇️"
        echo "https://docs.github.com/es/developers/overview/managing-deploy-keys#deploy-keys"
        echo ""
        echo "👇️ ¿ eres colaborador del proyecto ? 👇️"
        echo "https://docs.github.com/es/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account"
        echo ""
        break
    else
        echo "😑 email inválido !!"
        echo ""
    fi
done