#!/bin/bash

rm -f data/php/composer;

while true; do
    echo " - downloading PHP Composer";

    curl -o docker/bin/composer https://getcomposer.org/composer-stable.phar;

    if [ ! -f docker/bin/composer ]; then
        echo "Failed to download PHP Composer"
        sleep 7
    else
        chmod +x docker/bin/composer;
        echo "Downloaded success PHP Composer"
        break
    fi
done