#!/bin/bash
source /root/.bashrc

function is_false {
    if [ "$1" == "false" ] || [ "$1" == "False" ] || [ "$1" == "FALSE" ] || [ "$1" == "0" ]; then
        return 0
    else
        return 1
    fi
}

CNF_APP_ENV=${APP_ENV:-local}

if [ ! -f /var/www/.env ]; then
    echo "File /www/.env not found. Exiting..."
    exit 1
fi

if [ $CNF_APP_ENV == "local" ]; then
    if [ -f /var/www/.env.local ]; then
        source /var/www/.env.local
    else
        source /var/www/.env
    fi
else
    if [ -f /var/www/.env.$CNF_APP_ENV ]; then
        source /var/www/.env.$CNF_APP_ENV
    else
        source /var/www/.env
    fi
fi

CNF_APP_DEBUG=${APP_DEBUG:-true}
CNF_APP_URL=${APP_URL:-"http://localhost"}
CNF_APP_HOST=$(/usr/bin/php -r "echo parse_url('${CNF_APP_URL}', PHP_URL_HOST);")
CNF_APP_TIMEZONE=${APP_TIMEZONE:-"UTC"}
CNF_APP_SELF_CERT=${APP_SELF_CERT:-true}

if [[ "${CNF_APP_URL}" =~ ^https:// ]]; then
    CNF_APP_SSL=${APP_SSL:-true}
else
    CNF_APP_SSL=${APP_SSL:-false}
fi

CNF_SOKETI_PATH=$(which soketi);
CNF_SOKETI_PORT=${SOKETI_PORT:-6002}
CNF_SOKETI_ID=${SOKETI_ID:-"some-id"}
CNF_SOKETI_KEY=${SOKETI_KEY:-"some-key"}
CNF_SOKETI_SECRET=${SOKETI_SECRET:-"some-secret"}
CNF_SOKETI_WEBHOOK=${SOKETI_WEBHOOK:-"http://localhost:8080"}

echo "Starting Soketi..."
echo $(jq '.debug = '$CNF_APP_DEBUG' | .port = '$CNF_SOKETI_PORT' | ."appManager.array.apps.0.id" = "'$CNF_SOKETI_ID'" | ."appManager.array.apps.0.key" = "'$CNF_SOKETI_KEY'" | ."appManager.array.apps.0.secret" = "'$CNF_SOKETI_SECRET'" | ."appManager.array.apps.0.webhooks"[0].url = "'$CNF_SOKETI_WEBHOOK'"' /var/soketi/config.json) > /var/soketi/config.json
echo "Soketi started"

if [ $CNF_APP_SSL == true ] && [ $CNF_APP_SELF_CERT == true ]; then
    echo "Starting SSL certificate..."

    CNF_APP_IP=$(/bin/hostname -I | /usr/bin/awk '{print $1}')
    sed -e 's/__APP_HOST__/'$CNF_APP_HOST'/' -i /etc/ssl/sancert.cnf
    sed -e 's/__APP_IP__/'$CNF_APP_IP'/' -i /etc/ssl/sancert.cnf

    openssl dhparam -out /etc/ssl/certs/laravel.pem 2048
    openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
    -subj "/C=PE/ST=Lima/O=Byancode S.A.C/CN="${CNF_APP_HOST} \
    -out /etc/ssl/certs/laravel.crt \
    -keyout /etc/ssl/certs/laravel.key
    echo "SSL certificate generated"
fi

# configure timezone
ln -snf /usr/share/zoneinfo/${CNF_APP_TIMEZONE} /etc/localtime
echo ${CNF_APP_TIMEZONE} > /etc/timezone
echo "Timezone configured"

# defive octane server
sed -e 's@__SOKETI__@'$CNF_SOKETI_PATH'@' -i /var/config/doravel-soketi.conf
echo "Soketi configured"

sed -e 's/__APP_ENV__/'$CNF_APP_ENV'/' -i /etc/nginx/sites-available/ssl-fpm.conf
sed -e 's/__APP_ENV__/'$CNF_APP_ENV'/' -i /etc/nginx/sites-available/fpm.conf
sed -e 's/__APP_ENV__/'$CNF_APP_ENV'/' -i /var/config/doravel-octane.conf
echo "Environment configured"

sed -e 's/__APP_HOST__/'$CNF_APP_HOST'/' -i /etc/nginx/sites-available/fpm.conf
sed -e 's/__APP_HOST__/'$CNF_APP_HOST'/' -i /etc/nginx/sites-available/site.conf
sed -e 's/__APP_HOST__/'$CNF_APP_HOST'/' -i /etc/nginx/sites-available/soketi.conf
sed -e 's/__APP_HOST__/'$CNF_APP_HOST'/' -i /etc/nginx/sites-available/ssl-fpm.conf
sed -e 's/__APP_HOST__/'$CNF_APP_HOST'/' -i /etc/nginx/sites-available/ssl-site.conf
sed -e 's/__APP_HOST__/'$CNF_APP_HOST'/' -i /etc/nginx/sites-available/ssl-soketi.conf
echo "Host configured"

if [ $CNF_APP_SSL == true ] ; then \
    rm -f /etc/nginx/sites-available/fpm.conf;
    rm -f /etc/nginx/sites-available/site.conf;
    rm -f /etc/nginx/sites-available/soketi.conf;
else
    rm -f /etc/nginx/sites-available/ssl-fpm.conf;
    rm -f /etc/nginx/sites-available/ssl-site.conf;
    rm -f /etc/nginx/sites-available/ssl-soketi.conf;
fi
echo "SSL configured"

chown -R apache:apache storage
chown -R apache:apache bootstrap/cache
echo "Storage and cache directories configured"

if [ ! -d /var/www/vendor ]; then
    composer install
fi

if [ ! -d /var/www/node_modules ]; then
    npm install
fi

if [ ! -L /var/www/public/storage ]; then
    php artisan storage:link
fi

if is_false ${DORAVEL_SCHEDULE_DISABLE:-0}; then
    cat /var/config/doravel-schedule.conf >> /etc/supervisord.conf
fi

if is_false ${DORAVEL_FPM_DISABLE:-0}; then
    cat /var/config/doravel-fpm.conf >> /etc/supervisord.conf
else
    rm -f /etc/nginx/sites-available/fpm.conf
    rm -f /etc/nginx/sites-available/ssl-fpm.conf
fi

if is_false ${DORAVEL_OCTANE_DISABLE:-0}; then
    cat /var/config/doravel-octane.conf >> /etc/supervisord.conf
else
    rm -f /etc/nginx/sites-available/site.conf
    rm -f /etc/nginx/sites-available/ssl-site.conf
fi

if is_false ${DORAVEL_DEPLOY_DISABLE:-0}; then
    cat /var/config/doravel-deploy.conf >> /etc/supervisord.conf
    /git-pull # creamos conexion ssh para git
fi

if is_false ${DORAVEL_SOKETI_DISABLE:-0}; then
    cat /var/config/doravel-soketi.conf >> /etc/supervisord.conf
else
    rm -f /etc/nginx/sites-available/soketi.conf
    rm -f /etc/nginx/sites-available/ssl-soketi.conf
fi

if is_false ${DORAVEL_NGINX_DISABLE:-0}; then
    cat /var/config/doravel-nginx.conf >> /etc/supervisord.conf
fi

if [ -f /var/www/supervisord.conf ]; then
    cat /var/www/supervisord.conf >> /etc/supervisord.conf
fi

if [ $# -eq 0 ]; then
    echo "Starting supervisord..."
    /usr/bin/supervisord -n -c /etc/supervisord.conf
else
    exec "$@"
fi