#!/bin/bash
source /root/.bashrc

APP_ENV=${APP_ENV:-local}
source $(get_env_file $APP_ENV)

gum spin --spinner dot --title "composer install..." -- composer install --quiet --no-interaction --no-progress
gum log --time rfc822 --level info "Composer dependencies installed"

if [ -z "$APP_KEY" ]; then
    artisan key:generate --quiet --force
    gum log --time rfc822 --level info "APP_KEY generated"
fi
if [ ! -L "public/storage" ]; then
    artisan storage:link --quiet --force
    gum log --time rfc822 --level info "public/storage linked"
fi

gum spin --spinner dot --title "npm install..." -- npm install
gum log --time rfc822 --level info "NPM dependencies installed"