#!/bin/bash

DIRECTORY=$1
shift 1

if [ -z "$DIRECTORY" ]; then
    echo "Project directory is required"
    exit 1
fi

if [ "$DIRECTORY" != '.' ] && [ -d "$DIRECTORY" ]; then
    echo "Directory $DIRECTORY already exists"
    exit 1
fi

BRANCH="11.x"
mkdir -p "$DIRECTORY";

LARAVEL_FILE="$BRANCH.tar.gz"
LARAVEL_TMP_FILE="/tmp/$LARAVEL_FILE"

curl -L "https://github.com/laravel/laravel/archive/refs/heads/$LARAVEL_FILE" \
     -o "$LARAVEL_TMP_FILE";

tar -xzf "$LARAVEL_TMP_FILE" -C "$DIRECTORY" --strip-components=1;
rm -f "$LARAVEL_TMP_FILE";

if [  "$DIRECTORY" != '.'  ]; then
    cd $DIRECTORY
fi

/usr/doravel/bin/setup
exit $?