#!/bin/bash
source /root/.bashrc

DIRECTORY=$1
shift 1

if [ -z "$DIRECTORY" ]; then
    gum log --time rfc822 --level error "Project directory is required"
    exit 1
fi

if [ "$DIRECTORY" != '.' ] && [ -d "$DIRECTORY" ]; then
    gum log --time rfc822 --level error "Directory $DIRECTORY already exists"
    exit 1
fi

BRANCH="11.x"
mkdir -p "$DIRECTORY";

LARAVEL_FILE="$BRANCH.tar.gz"
LARAVEL_TMP_FILE="/tmp/$LARAVEL_FILE"

gum spin --spinner dot --title "Laravel $BRANCH downloading..." -- \
    curl -sL "https://github.com/laravel/laravel/archive/refs/heads/$LARAVEL_FILE" \
     -o "$LARAVEL_TMP_FILE";

gum spin --spinner dot --title "Laravel $BRANCH Installing..." -- \
    tar -xzf "$LARAVEL_TMP_FILE" -C "$DIRECTORY" --strip-components=1;
rm -f "$LARAVEL_TMP_FILE";

gum log --time rfc822 --level info "Laravel $BRANCH installed"

cd "$DIRECTORY";