#!/bin/bash
source /root/.bashrc

PROJECT_NAME=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 6 | head -n 1)
ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project-name)
            PROJECT_NAME=$2
            shift 2
            ;;
        *)
            ARGS+=("$1")
            shift
            ;;
    esac
done

recursive_cp() {
    ROOT_PATH=$1
    DEST_PATH=$2
    ORIGIN_PATH=$ROOT_PATH$DEST_PATH

    for FROM_PATH in $(find $ORIGIN_PATH); do
        TARGET_PATH=${FROM_PATH#$ROOT_PATH}
        if [ -d $FROM_PATH ]; then
            mkdir -p $TARGET_PATH
        elif [ ! -f $TARGET_PATH ]; then
            cp -f $FROM_PATH $TARGET_PATH
        fi
    done
}

if [ -f /root/.stubs/README.md ]; then
    cp -f /root/.stubs/README.md README.md
fi

if [ -f /usr/local/bin/doravel ]; then
    cp -f /usr/local/bin/doravel doravel
    sed -i 's/^PROJECT_NAME=.*/PROJECT_NAME="'$PROJECT_NAME'"/' doravel
fi

recursive_cp /root/ .planning/
recursive_cp /root/ .doravel/
recursive_cp /root/ .vscode/
recursive_cp /root/ .flows/

touch database/database.sqlite

/usr/doravel/bin/init local
/usr/doravel/bin/destroy example --force
