#!/bin/bash

dnf remove docker \
           docker-client \
           docker-client-latest \
           docker-common \
           docker-latest \
           docker-latest-logrotate \
           docker-logrotate \
           docker-selinux \
           docker-engine-selinux \
           docker-engine

dnf -y install dnf-plugins-core

dnf config-manager \
    --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
dnf -y install git expect

systemctl start docker