version: '3.1'
services:
    app:
        restart: on-failure
        image: laravel/app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_ENV: ${APP_ENV:-local}
        volumes:
            - .:/var/www
        ports:
            - ${APP_PORT:-80}:80
        networks:
            - default
        depends_on:
            - memcached
            - soketi
            - mysql
            - redis
        links:
            - minio
            - mailpit
            - meilisearch
    mysql:
        restart: on-failure
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
            MYSQL_DATABASE: ${DB_DATABASE:-doravel}
            MYSQL_USER: ${DB_USERNAME:-doravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_TCP_PORT: ${DB_PORT:-3306}
        expose:
            - ${DB_PORT:-3306}
        volumes:
            - data-mysql:/var/lib/mysql
        networks:
            - default
    redis:
        restart: on-failure
        image: redis
        volumes:
            - data-redis:/data
        expose:
            - 6379
        networks:
            - default
    minio:
        restart: on-failure
        image: minio/minio
        expose:
            - 9000
        ports:
            - ${MINIO_CONSOLE_PORT:-8900}:8900
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
        volumes:
            - data-minio:/data/minio
        networks:
            - default
        command: minio server /data/minio --console-address ":${MINIO_CONSOLE_PORT:-8900}"
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            retries: 3
            timeout: 5s
    mailpit:
        restart: on-failure
        image: axllent/mailpit
        expose:
            - 1025
        ports:
            - "${MAILPIT_DASHBOARD_PORT:-8025}:8025"
    meilisearch:
        restart: on-failure
        image: getmeili/meilisearch
        expose:
            - 7700
        ports:
            - ${MEILISEARCH_PORT:-7700}:7700
        volumes:
            - data-meilisearch:/meili_data
        networks:
            - default
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:7700/health']
            retries: 3
            timeout: 5s
    memcached:
        restart: on-failure
        image: memcached:alpine
        expose:
            - 11211
        networks:
            - default
    soketi:
        restart: on-failure
        image: quay.io/soketi/soketi:latest-16-alpine
        environment:
            SOKETI_DEBUG: 1
            SOKETI_METRICS_SERVER_PORT: ${SOKETI_METRICS_SERVER_PORT:-9601}
        expose:
            - 6001
        ports:
            - ${SOKETI_PORT:-6001}:6001
            - ${SOKETI_METRICS_SERVER_PORT:-9601}:9601
        networks:
            - default
    phpmyadmin:
        restart: on-failure
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: ${DB_HOST:-mysql}
            PMA_PORT: ${DB_PORT:-3306}
            PMA_USER: ${DB_USERNAME:-root}
            PMA_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
        ports:
            - ${PHPMYADMIN_PORT:-8080}:80
        networks:
            - default
        depends_on:
            - mysql
networks:
    default:
        driver: bridge
volumes:
    data-meilisearch:
    data-mysql:
    data-redis:
    data-minio:
