services:
    app:
        restart: on-failure
        image: ${DOCKER_IMAGE_REPOSITORY}:${DOCKER_IMAGE_TAG}
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_ENV: ${APP_ENV:-local}
        volumes:
            - .:/var/www
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - ${APP_PORT:-80}:80
            - ${VITE_PORT:-5173}:5173
        networks:
            - default
        depends_on:
            - memcached
            - postgres
            - redis
    redis:
        restart: on-failure
        image: redis
        volumes:
            - data-redis:/data
        expose:
            - 6379
        networks:
            - default
    minio:
        restart: on-failure
        image: minio/minio
        expose:
            - 9000
        ports:
            - ${MINIO_CONSOLE_PORT:-8900}:8900
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
        volumes:
            - data-minio:/data/minio
        networks:
            - default
        command: minio server /data/minio --console-address ":${MINIO_CONSOLE_PORT:-8900}"
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            retries: 3
            timeout: 5s
    mailpit:
        restart: on-failure
        image: axllent/mailpit
        expose:
            - 1025
        ports:
            - "${MAILPIT_DASHBOARD_PORT:-8025}:8025"
    meilisearch:
        restart: on-failure
        image: getmeili/meilisearch
        expose:
            - 7700
        ports:
            - ${MEILISEARCH_PORT:-7700}:7700
        volumes:
            - data-meilisearch:/meili_data
        networks:
            - default
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:7700/health']
            retries: 3
            timeout: 5s
    memcached:
        restart: on-failure
        image: memcached:alpine
        expose:
            - 11211
        networks:
            - default
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        expose:
            - 5432
        volumes:
            - data-postgres:/var/lib/postgresql
        networks:
            - default
    pgadmin:
        image: dpage/pgadmin4
        environment:
            CONFIG_DATABASE_URI: postgresql://$DB_USERNAME:$DB_PASSWORD@postgres:5432/$DB_DATABASE
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-hello@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-secret}
        ports:
            - ${PGADMIN_PORT:-8080}:80
        networks:
            - default
        depends_on:
            - postgres
        volumes:
          - data-pgadmin:/var/lib/pgadmin
networks:
    default:
        driver: bridge
volumes:
    data-meilisearch:
    data-postgres:
    data-pgadmin:
    data-redis:
    data-minio:
