version: '3.1'
services:
    app:
        image: byancode/doravel:php-8.1
        environment:
            GIT_EMAIL: $GIT_EMAIL
            GIT_NAME: $GIT_NAME
            APP_ENV: ${APP_ENV:-local}
        volumes:
            - .:/var/www
        ports:
            - 80:80
            - 443:443
        networks:
            - default
        depends_on:
            - memcached
            - soketi
            - mysql
            - redis
        links:
            - minio
            - mailhog
            - meilisearch
    mysql:
        image: mariadb
        environment:
            MYSQL_TCP_PORT: 3307
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_USER: $DB_USERNAME
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        expose:
            - 3307
        volumes:
            - data-mariadb:/var/lib/mysql
        networks:
            - default
    redis:
        image: redis
        volumes:
            - data-redis:/data
        expose:
            - 6379
        networks:
            - default
    minio:
        image: minio/minio
        expose:
            - 9000
        ports:
            - ${MINIO_CONSOLE_PORT:-8900}:8900
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
        volumes:
            - data-minio:/data/minio
        networks:
            - default
        command: minio server /data/minio --console-address ":${MINIO_CONSOLE_PORT:-8900}"
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            retries: 3
            timeout: 5s
    mailhog:
        image: mailhog/mailhog
        expose:
            - 1025
        ports:
            - ${MAILHOG_DASHBOARD_PORT:-8025}:8025
        networks:
            - default
    meilisearch:
        image: getmeili/meilisearch
        ports:
            - ${MEILISEARCH_PORT:-7700}:7700
        volumes:
            - data-meilisearch:/meili_data
        networks:
            - default
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:7700/health']
            retries: 3
            timeout: 5s
    memcached:
        image: memcached:alpine
        expose:
            - 11211
        networks:
            - default
    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        environment:
            SOKETI_DEBUG: 1
            SOKETI_METRICS_SERVER_PORT: 9601
        ports:
            - ${SOKETI_PORT:-6001}:6001
            - ${SOKETI_METRICS_SERVER_PORT:-9601}:9601
        networks:
            - default
networks:
    default:
        driver: bridge
volumes:
    data-meilisearch:
    data-mariadb:
    data-mysql:
    data-redis:
    data-minio:
