services:
    app:
        restart: on-failure
        image: ${DOCKER_IMAGE_REPOSITORY}:${DOCKER_IMAGE_TAG}
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_ENV: $APP_ENV
            NETWORK_IP: $NETWORK_IP
            DOCKER_SOCK_FILE: $DOCKER_SOCK_FILE
        command: doraveld
        volumes:
            - $DOCKER_SOCK_FILE:/var/run/docker.sock
            - .:/var/www
        ports:
            - ${APP_PORT:-80}:8000
            - ${REVERB_PORT:-8080}:9000
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        networks:
            - doravel
        depends_on:
            - memcached
            - postgres
            - mysql
            - redis
    redis:
        restart: on-failure
        image: redis:${REDIS_VERSION:-latest}
        volumes:
            - data-redis:/data
        expose:
            - 6379
        networks:
            - doravel
    minio:
        restart: on-failure
        image: minio/minio:${MINIO_VERSION:-latest}
        expose:
            - 9000
        ports:
            - ${MINIO_CONSOLE_PORT:-8900}:8900
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
        volumes:
            - data-minio:/data/minio
        networks:
            - doravel
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            retries: 3
            timeout: 5s
    mailpit:
        restart: on-failure
        image: axllent/mailpit:${MAILPIT_VERSION:-latest}
        labels:
            - env.MAIL_HOST=mailpit
        expose:
            - 1025
        ports:
            - ${MAILPIT_DASHBOARD_PORT:-8025}:8025
        networks:
            - doravel
    meilisearch:
        restart: on-failure
        image: getmeili/meilisearch:${MEILISEARCH_VERSION:-latest}
        expose:
            - 7700
        ports:
            - ${MEILISEARCH_PORT:-7700}:7700
        volumes:
            - data-meilisearch:/meili_data
        networks:
            - doravel
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:7700/health']
            retries: 3
            timeout: 5s
    memcached:
        restart: on-failure
        image: memcached:${MEMCACHED_VERSION:-latest}
        expose:
            - 11211
        networks:
            - doravel
    postgres:
        restart: on-failure
        image: postgres:${POSTGRES_VERSION:-latest}
        environment:
            TZ: $APP_TIMEZONE
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        labels:
            - env.DB_CONNECTION=pgsql
            - env.DB_HOST=postgres
        expose:
            - 5432
        volumes:
            - data-postgres:/var/lib/postgresql
        networks:
            - doravel
    pgadmin:
        restart: on-failure
        image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
        environment:
            CONFIG_DATABASE_URI: postgresql://$DB_USERNAME:$DB_PASSWORD@postgres:5432/$DB_DATABASE
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-hello@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-secret}
        ports:
            - ${PGADMIN_PORT:-8080}:80
        depends_on:
            - postgres
        volumes:
            - data-pgadmin:/var/lib/pgadmin
        networks:
            - doravel
    mysql:
        restart: on-failure
        image: mysql:${MYSQL_VERSION:-8}
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
            MYSQL_DATABASE: ${DB_DATABASE:-doravel}
            MYSQL_USER: ${DB_USERNAME:-doravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_TCP_PORT: ${DB_PORT:-3306}
        expose:
            - ${DB_PORT:-3306}
        labels:
            - env.DB_CONNECTION=mysql
            - env.DB_HOST=mysql
        volumes:
            - data-mysql:/var/lib/mysql
        networks:
            - doravel
    phpmyadmin:
        restart: on-failure
        image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
        environment:
            PMA_HOST: ${DB_HOST:-mysql}
            PMA_PORT: ${DB_PORT:-3306}
            PMA_USER: ${DB_USERNAME:-root}
            PMA_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
        ports:
            - ${PHPMYADMIN_PORT:-8080}:80
        networks:
            - doravel
        depends_on:
            - mysql
networks:
    doravel:
        driver: bridge
volumes:
    data-meilisearch:
    data-postgres:
    data-pgadmin:
    data-mysql:
    data-redis:
    data-minio:
