#!/bin/ash
# ESTE ARCHIVO SE CARGARA AL EJECUTAR CUALQUIER SHELL
#
# EXPORT ENVIRONMENT VARIABLES
#
if ! exist_path "$APP_PATH/.doravel/bin"; then
    export PATH="$APP_PATH/.doravel/bin:$PATH"
fi
#
# SET ALIAS FOR COMMANDS
#
alias ll="ls -alF"
alias d="doravel"
alias a="doravel $APP_ENV artisan"
alias c="doravel $APP_ENV composer"
alias s="doravel $APP_ENV supervisorctl"

PS1='\[\e[31m\]$APP_ENV\[\e[0m\]:\w\$ '
