#!/bin/bash

if [ ! -d ./storage ] || [ ! -d ./bootstrap ] || [ ! -d ./resources ] || [ ! -d ./routes ] || [ ! -d ./app ]; then
    echo "this not is a doravel project"
    exit 0
fi


ENDPOINT="https://raw.githubusercontent.com/byancode/doravel/main"

askOverrideFile() {
    INPUT=$1
    OUTPUT=$2

    if [ -z "$OUTPUT" ]; then
        OUTPUT=$INPUT
    fi

    RESPONSE='y'
    if [ -f ./$OUTPUT ]; then
        read -p "¿Desea sobreescribir $OUTPUT? (y/n): " RESPONSE
    fi
    if [ "$RESPONSE" == 'y' ] && [ -f ./$OUTPUT ]; then
        TIMESPAMP=$(date +%s)
        mkdir ./.doravel
        cp ./$OUTPUT ./.doravel/backup_${TIMESPAMP}_${OUTPUT}
    fi
    if [ "$RESPONSE" == 'y' ]; then
        curl -s ${ENDPOINT}/stubs/$INPUT > ./$OUTPUT
    fi
}

touch ./supervisord.conf
askOverrideFile .env .env
askOverrideFile Dockerfile Dockerfile
askOverrideFile docker-compose.yml docker-compose.local.yml

if ! [ -f ./.env.prod ]; then
    read -p "¿Desea agregar un entorno de produccion? (y/n): " RESPONSE
    if [ "$RESPONSE" == 'y' ]; then
        touch ./supervisord.prod.conf
        askOverrideFile .env.prod .env.prod
        askOverrideFile Dockerfile.prod Dockerfile.prod
        askOverrideFile docker-compose.yml docker-compose.prod.yml
    fi
fi

if ! [ -f ./.env.main ]; then
    read -p "¿Desea agregar un entorno master? (y/n): " RESPONSE
    if [ "$RESPONSE" == 'y' ]; then
        touch ./supervisord.main.conf
        askOverrideFile .env.main .env.main
        askOverrideFile Dockerfile.main Dockerfile.main
        askOverrideFile docker-compose.yml docker-compose.main.yml
    fi
fi

if ! [ -f ./.env.test ]; then
    read -p "¿Desea agregar un entorno de testing? (y/n): " RESPONSE
    if [ "$RESPONSE" == 'y' ]; then
        touch ./supervisord.test.conf
        askOverrideFile .env.test .env.test
        askOverrideFile Dockerfile.test Dockerfile.test
        askOverrideFile docker-compose.yml docker-compose.test.yml
    fi
fi

if [ -f ./doravel ]; then
    rm -f ./doravel
fi

curl -O ${ENDPOINT}/bin/doravel
chmod +x ./doravel

if [ ! -d ./vendor ]; then
    composer install
fi

if [ ! -d ./vendor/laravel/octane ]; then
    IMAGE_NAME=$(cat Dockerfile | grep "FROM" | awk '{print $2}')
    docker run --rm -it -v $(pwd):/var/www $(echo $IMAGE_NAME) composer require laravel/octane --with-all-dependencies
    docker run --rm -it -v $(pwd):/var/www $(echo $IMAGE_NAME) php artisan octane:install --server=swoole
fi