#!/bin/bash

if [ ! -d ./storage ] || [ ! -d ./bootstrap ] || [ ! -d ./resources ] || [ ! -d ./routes ] || [ ! -d ./app ]; then
    echo "this not is a doravel project"
    exit 0
fi

ENDPOINT="https://raw.githubusercontent.com/byancode/doravel/main"

askOverrideFile() {
    INPUT=$1
    OUTPUT=$2

    if [ -z "$OUTPUT" ]; then
        OUTPUT=$INPUT
    fi

    RESPONSE='y'
    if [ -f ./$OUTPUT ]; then
        read -p "¿Desea sobreescribir $OUTPUT? (y/n): " RESPONSE
    fi
    if [ "$RESPONSE" == 'y' ] && [ -f ./$OUTPUT ]; then
        TIMESPAMP=$(date +%s)
        mkdir -p ./.doravel/backups/${TIMESPAMP}
        cp ./$OUTPUT ./.doravel/backups/${TIMESPAMP}/${OUTPUT}
    fi
    if [ "$RESPONSE" == 'y' ]; then
        curl -s ${ENDPOINT}/stubs/$INPUT > ./$OUTPUT
    fi
}

ENV_NAME=local
touch ./supervisord.conf
askOverrideFile .env .env
askOverrideFile Dockerfile Dockerfile
askOverrideFile docker-compose.yaml docker-compose.yaml

ENV_NAME=prod
if ! [ -f ./.env.$ENV_NAME ]; then
    read -p "¿Desea agregar un entorno de produccion? (y/n): " RESPONSE
    if [ "$RESPONSE" == 'y' ]; then
        touch ./supervisord.$ENV_NAME.conf
        askOverrideFile .env .env.$ENV_NAME
        askOverrideFile Dockerfile Dockerfile.$ENV_NAME
        askOverrideFile docker-compose.yaml docker-compose.$ENV_NAME.yaml
    fi
fi

ENV_NAME=dev
if ! [ -f ./.env.$ENV_NAME ]; then
    read -p "¿Desea agregar un entorno de development? (y/n): " RESPONSE
    if [ "$RESPONSE" == 'y' ]; then
        touch ./supervisord.$ENV_NAME.conf
        askOverrideFile .env .env.$ENV_NAME
        askOverrideFile Dockerfile Dockerfile.$ENV_NAME
        askOverrideFile docker-compose.yaml docker-compose.$ENV_NAME.yaml
    fi
fi

curl -O ${ENDPOINT}/bin/doravel
chmod +x ./doravel

if [ ! -d ./vendor ]; then
    IMAGE_NAME=$(cat Dockerfile | grep "FROM" | awk '{print $2}')
    docker run --rm -it -v $(pwd):/var/www $(echo $IMAGE_NAME) initialize
fi