#!/bin/bash

DISTRO=$(cat /etc/os-release | grep "^ID=" | cut -d= -f2)
DISTRO=${DISTRO//\"/}

if  [ "$DISTRO" == "ubuntu" ] || [ "$DISTRO" == "debian" ]; then
    sudo apt-get update
elif [ "$DISTRO" == "centos" ] || [ "$DISTRO" == "rhel" ]; then
    sudo yum update
elif [ "$DISTRO" == "fedora" ]; then
    sudo dnf update
else
    echo "Distro not supported"
    exit 1
fi

if ! [ -x "$(command -v curl)" ]; then
    if  [ "$DISTRO" == "ubuntu" ] || [ "$DISTRO" == "debian" ]; then
        sudo apt-get install -y curl
    elif [ "$DISTRO" == "centos" ] || [ "$DISTRO" == "rhel" ]; then
        sudo yum install curl -y
    elif [ "$DISTRO" == "fedora" ]; then
        sudo dnf install curl -y
    fi
fi
if ! [ -x "$(command -v git)" ]; then
    if  [ "$DISTRO" == "ubuntu" ] || [ "$DISTRO" == "debian" ]; then
        sudo apt-get install -y git
    elif [ "$DISTRO" == "centos" ] || [ "$DISTRO" == "rhel" ]; then
        sudo yum install git -y
    elif [ "$DISTRO" == "fedora" ]; then
        sudo dnf install git -y
    fi
fi
if ! [ -x "$(command -v unzip)" ]; then
    if  [ "$DISTRO" == "ubuntu" ] || [ "$DISTRO" == "debian" ]; then
        sudo apt-get install -y unzip
    elif [ "$DISTRO" == "centos" ] || [ "$DISTRO" == "rhel" ]; then
        sudo yum install unzip -y
    elif [ "$DISTRO" == "fedora" ]; then
        sudo dnf install unzip -y
    fi
fi
if ! [ -x "$(command -v docker)" ]; then
    read -p "¿Desea instalar docker? (y/n): " RESPONSE
    if [ "$RESPONSE" != 'y' ]; then
        echo "Docker is not installed"
        exit 1
    fi
    curl https://get.docker.com | bash
fi

ENDPOINT="https://raw.githubusercontent.com/byancode/doravel/main"

if [ ! -d ~/bin ]; then
    mkdir ~/bin
fi

curl -s $ENDPOINT/bin/doravel -o ~/bin/doravel
curl -s $ENDPOINT/bin/dlocal -o ~/bin/dlocal

chmod +x ~/bin/d*

if [ -f ~/bin/doravel ]; then
    ln -sf ~/bin/doravel ~/bin/dv
fi

if ! grep -q "export PATH=\$PATH:\$HOME/bin" ~/.bashrc; then
    echo "" >> ~/.bashrc
    echo "export PATH=\$PATH:\$HOME/bin" >> ~/.bashrc
    echo "" >> ~/.bashrc
fi

source ~/.bashrc
