#!/bin/bash

ENDPOINT="https://raw.githubusercontent.com/byancode/doravel/main"

curl -s $ENDPOINT/scripts/install | bash
source ~/.bashrc

GIT_URL=$(git config --get remote.origin.url)
GIT_NAME=$(git config --get user.name)
GIT_EMAIL=$(git config --get user.email)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ ! "$GIT_URL" =~ \.git$ ]]; then
    echo "El repositorio no es correcto"
    exit 1
fi

if [ -z "$GIT_BRANCH" ]; then
    read -p "Ingrese el nombre del branch: " GIT_BRANCH
    if [[ ! $GIT_BRANCH =~ ^[a-zA-Z0-9_-]+$ ]]; then
        echo "El nombre del branch no es correcto"
        exit 1
    fi
fi

if [ -z "$GIT_NAME" ]; then
    read -p "Ingrese su nombre: " GIT_NAME
    if [ -z "$GIT_NAME" ]; then
        echo "El nombre no puede estar vacio"
        exit 1
    fi
fi

if [ -z "$GIT_EMAIL" ]; then
    read -p "Ingrese su email: " GIT_EMAIL
    if [[ ! $GIT_EMAIL =~ ^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$ ]]; then
        echo "El email no es correcto"
        exit 1
    fi
fi

if [ ! -f ./storage/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -b 4096 -C "$GIT_EMAIL" -f ./storage/.ssh/id_rsa -q -N ""
    chmod 600 ./storage/.ssh/id_rsa
fi

echo ""
echo "##🔑 SSH key generated 🔑##"
echo ""
cat ./storage/.ssh/id_rsa.pub
echo ""
echo ""
echo "⚠️⚠️ IMPORTANTE ⚠️⚠️"
echo "No olvide agregar la clave pública a su repositorio de GitHub!"
echo "👇️ Documentacion de DEPLOY KEYS 👇️"
echo ""
echo "https://docs.github.com/es/developers/overview/managing-deploy-keys#deploy-keys"
echo ""

RSA_KEY=$(cat ./storage/.ssh/id_rsa | base64 --wrap=0)
RSA_PUB=$(cat ./storage/.ssh/id_rsa.pub | base64 --wrap=0)

curl -O ${ENDPOINT}/stubs/deploy

sed -e 's~__RSA_KEY__~'$RSA_KEY'~' -i ./deploy
sed -e 's~__RSA_PUB__~'$RSA_PUB'~' -i ./deploy
sed -e 's~__GIT_URL__~'$GIT_URL'~' -i ./deploy
sed -e 's~__GIT_NAME__~'$GIT_NAME'~' -i ./deploy
sed -e 's~__GIT_EMAIL__~'$GIT_EMAIL'~' -i ./deploy
sed -e 's~__GIT_BRANCH__~'$GIT_BRANCH'~' -i ./deploy

chmod +x ./deploy

curl -s $ENDPOINT/scripts/init | bash
source ~/.bashrc

find . -name 'Dockerfile*' | while read FILE; do
    sed -e 's~__GIT_NAME__~'$GIT_NAME'~' -i $FILE
    sed -e 's~__GIT_EMAIL__~'$GIT_EMAIL'~' -i $FILE
done