#!/bin/bash

PACKAGES="curl git unzip jq";
MANAGER="";

if [ -x "$(command -v sudo)" ]; then
    MANAGER="sudo";
fi

if [ -x "$(command -v apt)" ]; then
    MANAGER="$MANAGER apt";
    $MANAGER update;
    $MANAGER install -y $PACKAGES;
elif [ -x "$(command -v dnf)" ]; then
    MANAGER="$MANAGER dnf";
    $MANAGER update;
    $MANAGER install -y $PACKAGES;
elif [ -x "$(command -v yum)" ]; then
    MANAGER="$MANAGER yum";
    $MANAGER update;
    $MANAGER install -y $PACKAGES;
elif [ -x "$(command -v apk)" ]; then
    MANAGER="$MANAGER apk";
    $MANAGER update;
    $MANAGER add $PACKAGES;
elif [ -x "$(command -v pacman)" ]; then
    MANAGER="$MANAGER pacman";
    $MANAGER -Sy;
    $MANAGER -S $PACKAGES;
else
    echo "Distro not supported"
    exit 1
fi

if [ -x "$(command -v sh)" ]; then
    INTERPRETER="sh"
elif [ -x "$(command -v bash)" ]; then
    INTERPRETER="bash"
fi

if ! [ -x "$(command -v docker)" ]; then
    read -p "¿Desea instalar docker? (y/n): " RESPONSE
    if [ "$RESPONSE" != 'y' ]; then
        echo "Docker is not installed"
        exit 1
    fi
    if [ -x "$INTERPRETER" ]; then
        curl https://get.docker.com | $(echo $INTERPRETER)
    else
        echo "El intérprete no es ejecutable"
        exit 1
    fi
fi

ENDPOINT="https://raw.githubusercontent.com/byancode/doravel/main"

if [ ! -d ~/bin ]; then
    mkdir ~/bin
fi

curl -s $ENDPOINT/bin/doravel -o ~/bin/doravel
curl -s $ENDPOINT/bin/dlocal -o ~/bin/dlocal

chmod +x ~/bin/d*

if [ -f ~/bin/doravel ]; then
    ln -sf ~/bin/doravel ~/bin/dv
fi

if ! grep -q "export PATH=\$PATH:\$HOME/bin" ~/.bashrc; then
    echo "" >> ~/.bashrc
    echo "export PATH=\$PATH:\$HOME/bin" >> ~/.bashrc
    echo "" >> ~/.bashrc
fi

source ~/.bashrc
