#!/bin/sh

EXTENSION="extension"
if [ "$2" == "--zend" ]; then
    EXTENSION="zend_extension"
fi

while true; do
    echo " - installing ${EXTENSION}=$1";
    # no generar ningun error ni finalizar el script con el siguiente comando "pecl install $1"
    pecl install $1 || true
    FILE=$(find /usr/local/lib/php/extensions/ -name $1.so | head -n 1)

    if [ -z "$FILE" ]; then
        echo "Failed to install $1"
        sleep 7
    else
        echo "${EXTENSION}=${FILE}" > /usr/local/etc/php/conf.d/docker-php-ext-$1.ini
        echo "Installed success $1" 
        break
    fi
done