#!/bin/sh

EXTENSION="extension"
PACKAGE="swoole"

while true; do
    echo " - installing ${EXTENSION}=${PACKAGE}";
    # no generar ningun error ni finalizar el script con el siguiente comando "pecl install $1"
    pecl install swoole
    FILE=$(find /usr/local/lib/php/extensions/ -name ${PACKAGE}.so | head -n 1)

    if [ -z "$FILE" ]; then
        echo "Failed to install ${PACKAGE}"
        sleep 7
    else
        echo "${EXTENSION}=${FILE}" > /usr/local/etc/php/conf.d/docker-php-ext-${PACKAGE}.ini
        echo "Installed success ${PACKAGE}"
        break
    fi
done